In [1]:

import sqlite3

conn = sqlite3.connect('emobility copy.db')

In [2]:
import pandas as pd

tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)

In [3]:
tables

                                                 name
0                    e_mobility_data_template_sow_4.1
1                               kenya_ev_stations_(1)
2                    e_mobility_data_template_sow_4_1
3   for_publication_africa_ev_readiness_impact_ind...
4                      unep_eac_emobility_gantt_chart
5                unep_eac_emobility_weekly_live_chart
6                                         battery_eol
7                                 country_qualitative
8                                       eac_countries
9                                           financing
10                                     fiscal_tariffs
11                             industrial_value_chain
12                   kenya_ev_charging_infrastructure
13                                kenya_ev_stations_1
14                                       market_fleet
15                                   policy_inventory
16                                      power_systems
17                      rwanda_ev_charging_stations_1
18                      tanzania_ev_charging_stations
19      transition_control_fuel_motorcycle_daily_data
20       transition_control_fuel_motorcycle_trip_data
21  transition_treatment_electric_motorcycle_daily...
22  transition_treatment_electric_motorcycle_trip_...
23                uganda_ev_charging_stations_dataset

In [4]:
bat = pd.read_sql("""SELECT * FROM battery_eol""", conn)
bat.head()

,country_iso,year,battery_chemistry,volume_units,collection_rate_pct,recycling_facility_count,regulatory_status,data_source,notes
0,KE,2024,LFP,5000,10,1,draft,EPRA,No formal EPR
1,KE,2024,lead_acid,15000,45,3,enacted,NEMA,Legacy ICE batteries
2,RW,2024,LFP,3000,15,1,draft,REMA,NaN
3,RW,2024,lead_acid,8000,40,2,enacted,REMA,Legacy ICE batteries
4,UG,2024,lead_acid,12000,35,2,absent,NEMA,Legacy ICE batteries

In [5]:
bat.columns

Index(['country_iso', 'year', 'battery_chemistry', 'volume_units',
       'collection_rate_pct', 'recycling_facility_count', 'regulatory_status',
       'data_source', 'notes'],
      dtype='str')

In [6]:
country_q = pd.read_sql("""SELECT * FROM country_qualitative""", conn)
country_q.head()

,country_iso,country_name,ev_market_stage,primary_segment,charging_infrastructure,data_availability,key_barrier,key_opportunity,notes
0,TZ,Tanzania,Early growth,2W and 3W,Sparse but expanding,Low,Registration enforcement gap,Urban 2W electrification,10k+ estimate; EWURA guidelines 2026
1,BI,Burundi,Nascent,All,Minimal,NaN,No grid access,Policy framework in place,ICE import ban planned 2027
2,SS,South Sudan,Nascent,All,NaN,NaN,No grid access,Hybrid bridge,Hybrids preferred; no EV policy
3,CD,DR Congo,Nascent,All,Minimal,NaN,No grid access,Hydro-powered charging,No EV policy; SNEL grid mostly hydro
4,SO,Somalia,Nascent,All,NaN,NaN,No grid access,Private sector imports,Small-scale importers; no government policy

In [7]:
country_q.columns

Index(['country_iso', 'country_name', 'ev_market_stage', 'primary_segment',
       'charging_infrastructure', 'data_availability', 'key_barrier',
       'key_opportunity', 'notes'],
      dtype='str')

In [8]:
eac = pd.read_sql("""SELECT * FROM eac_countries""", conn)
eac.head()

,country_iso,country_name,eac_partner_state,accession_year,population,gdp_usd,currency_code,notes
0,KE,Kenya,1,2000,55100586,113400000000,KES,Founding member
1,RW,Rwanda,1,2007,14100000,14100000000,RWF,NaN
2,UG,Uganda,1,2000,48600000,49200000000,UGX,Founding member
3,TZ,Tanzania,1,2000,67400000,79100000000,TZS,Founding member
4,BI,Burundi,1,2007,13200000,3000000000,BIF,NaN

In [9]:
eac.columns

Index(['country_iso', 'country_name', 'eac_partner_state', 'accession_year',
       'population', 'gdp_usd', 'currency_code', 'notes'],
      dtype='str')

In [10]:
fis = pd.read_sql("""SELECT * FROM fiscal_tariffs""", conn)
fis.head()

,country_iso,year,vehicle_segment,duty_rate_ice,duty_rate_ev,vat_rate_ice,vat_rate_ev,data_source,notes
0,KE,2024,all,25.0,10.0,16.0,0.0,Kenya Gazette,NaN
1,RW,2024,all,25.0,0.0,18.0,0.0,RRA,NaN
2,UG,2024,all,25.0,0.0,18.0,0.0,URA,NaN
3,TZ,2024,all,25.0,10.0,18.0,0.0,TRA,NaN
4,BI,2024,all,NaN,NaN,NaN,NaN,OBR,VAT and customs exempt

In [11]:
fis.columns

Index(['country_iso', 'year', 'vehicle_segment', 'duty_rate_ice',
       'duty_rate_ev', 'vat_rate_ice', 'vat_rate_ev', 'data_source', 'notes'],
      dtype='str')

In [12]:
ind = pd.read_sql("""SELECT * FROM industrial_value_chain""", conn)
ind.head()

,country_iso,year,value_chain_stage,company_name,capacity_units_year,employment_count,year_established,local_content_pct,data_source,notes
0,KE,2024,assembly,ROAM Motors,5000.0,250.0,2017.0,15.0,ROAM,NaN
1,KE,2024,assembly,Arc Ride,3000.0,150.0,2020.0,12.0,Arc Ride,NaN
2,KE,2024,battery,Powerhive,2000.0,120.0,2015.0,10.0,Powerhive,NaN
3,RW,2024,assembly,Ampersand,10000.0,400.0,2016.0,20.0,Ampersand,NaN
4,RW,2024,assembly,Volt Rwanda,2000.0,100.0,2019.0,15.0,Volt Rwanda,NaN

In [13]:
ind.columns

Index(['country_iso', 'year', 'value_chain_stage', 'company_name',
       'capacity_units_year', 'employment_count', 'year_established',
       'local_content_pct', 'data_source', 'notes'],
      dtype='str')

In [14]:
mar = pd.read_sql("""SELECT * FROM market_fleet""", conn)
mar.head()

,country_iso,year,vehicle_segment,propulsion_type,new_registrations,cumulative_stock,data_source,data_confidence,notes
0,KE,2020,all,BEV,NaN,300.0,EPRA,high,Baseline
1,KE,2021,all,BEV,NaN,584.0,EPRA,high,NaN
2,KE,2022,all,BEV,NaN,1059.0,EPRA,high,NaN
3,KE,2023,all,BEV,NaN,3753.0,EPRA,high,NaN
4,KE,2024,all,BEV,NaN,5294.0,EPRA,high,NaN

In [15]:
mar.columns

Index(['country_iso', 'year', 'vehicle_segment', 'propulsion_type',
       'new_registrations', 'cumulative_stock', 'data_source',
       'data_confidence', 'notes'],
      dtype='str')

In [16]:
pol = pd.read_sql("""SELECT * FROM policy_inventory""", conn)
pol.head()

  country_iso_year_enacted_policy_instrument_instrument_type_category_status_effective_date_vehicle_segment_description_data_source
0  KE,2023,Finance Act 2023 EV VAT Exemption,fisc...
1  KE,2023,Finance Act 2023 EV Duty Reduction,fis...
2  KE,2024,National E-Mobility Policy,regulatory,...
3  KE,2024,EPRA Charging Infrastructure Guideline...
4  RW,2024,Rwanda EV Incentive Framework,fiscal,V...

In [17]:
pol.columns

Index(['country_iso_year_enacted_policy_instrument_instrument_type_category_status_effective_date_vehicle_segment_description_data_source'], dtype='str')

In [18]:
print(pol.shape)
print(pol.columns.tolist())
print(pol.head())

(22, 1)
['country_iso_year_enacted_policy_instrument_instrument_type_category_status_effective_date_vehicle_segment_description_data_source']
  country_iso_year_enacted_policy_instrument_instrument_type_category_status_effective_date_vehicle_segment_description_data_source
0  KE,2023,Finance Act 2023 EV VAT Exemption,fisc...
1  KE,2023,Finance Act 2023 EV Duty Reduction,fis...
2  KE,2024,National E-Mobility Policy,regulatory,...
3  KE,2024,EPRA Charging Infrastructure Guideline...
4  RW,2024,Rwanda EV Incentive Framework,fiscal,V...

In [19]:
pol.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 1 columns):
 #   Column                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                             --------------  -----
 0   country_iso_year_enacted_policy_instrument_instrument_type_category_status_effective_date_vehicle_segment_description_data_source  22 non-null     str
dtypes: str(1)
memory usage: 308.0 bytes

In [22]:
cursor = conn.cursor()

cursor.execute("PRAGMA table_info(policy_inventory);")

for row in cursor.fetchall():
    print(row)

(0, 'country_iso_year_enacted_policy_instrument_instrument_type_category_status_effective_date_vehicle_segment_description_data_source', 'TEXT', 0, None, 0)

In [23]:
cursor.execute("SELECT * FROM policy_inventory LIMIT 5;")

for row in cursor.fetchall():
    print(row)

('KE,2023,Finance Act 2023 EV VAT Exemption,fiscal,VAT,enacted,2023-07-01,all,Exempts EVs from 16% VAT,Kenya Gazette',)
('KE,2023,Finance Act 2023 EV Duty Reduction,fiscal,import_duty,enacted,2023-07-01,all,Reduces EV import duty from 25% to 10%,Kenya Gazette',)
('KE,2024,National E-Mobility Policy,regulatory,target,draft,2024-01-01,all,5% EV adoption by 2030,MoR&T',)
('KE,2024,EPRA Charging Infrastructure Guidelines,regulatory,standard,enacted,2024-03-01,all,Technical standards for charging stations,EPRA',)
('RW,2024,Rwanda EV Incentive Framework,fiscal,VAT,enacted,2024-01-01,all,EVs exempt from VAT and import duty,RRA',)

In [24]:
row = cursor.execute(
    "SELECT * FROM policy_inventory LIMIT 1"
).fetchone()

fields = row[0].split(",")

print("Number of fields:", len(fields))

for i, field in enumerate(fields, 1):
    print(i, repr(field))

Number of fields: 10
1 'KE'
2 '2023'
3 'Finance Act 2023 EV VAT Exemption'
4 'fiscal'
5 'VAT'
6 'enacted'
7 '2023-07-01'
8 'all'
9 'Exempts EVs from 16% VAT'
10 'Kenya Gazette'

In [25]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS policy_inventory_backup AS
SELECT * FROM policy_inventory;
""")

conn.commit()

print("Backup created.")

Backup created.

In [29]:
rows = cursor.execute("SELECT * FROM policy_inventory").fetchall()

for i, row in enumerate(rows):
    print(f"\nROW {i}:")
    print(row[0])

ROW 0:
KE,2023,Finance Act 2023 EV VAT Exemption,fiscal,VAT,enacted,2023-07-01,all,Exempts EVs from 16% VAT,Kenya Gazette

ROW 1:
KE,2023,Finance Act 2023 EV Duty Reduction,fiscal,import_duty,enacted,2023-07-01,all,Reduces EV import duty from 25% to 10%,Kenya Gazette

ROW 2:
KE,2024,National E-Mobility Policy,regulatory,target,draft,2024-01-01,all,5% EV adoption by 2030,MoR&T

ROW 3:
KE,2024,EPRA Charging Infrastructure Guidelines,regulatory,standard,enacted,2024-03-01,all,Technical standards for charging stations,EPRA

ROW 4:
RW,2024,Rwanda EV Incentive Framework,fiscal,VAT,enacted,2024-01-01,all,EVs exempt from VAT and import duty,RRA

ROW 5:
RW,2025,Kigali ICE Motorcycle Ban,regulatory,ban,enacted,2025-01-01,2W,Bans new ICE motorcycle registrations in Kigali,RURA

ROW 6:
RW,2024,National E-Mobility Strategy,regulatory,target,enacted,2024-06-01,all,Targets 20% EV penetration by 2030,MININFRA

ROW 7:
UG,2024,National E-Mobility Strategy,regulatory,target,enacted,2024-06-01,2W,20% EV imports by 2030,MoWT

ROW 8:
UG,2024,EV Import Duty Exemption,fiscal,import_duty,enacted,2024-07-01,all,Full duty exemption for EVs,URA

ROW 9:
UG,2025,Kampala E-Motorcycle Mandate,regulatory,target,proposed,2026-01-01,2W,Proposed 100% electric motorcycle target,KCCA

ROW 10:
TZ,2024,Vehicle Registration Amendment,regulatory,standard,enacted,2024-07-01,all,Explicitly includes EVs in registration law,TRA

ROW 11:
TZ,2024,EV Import Duty Reduction,fiscal,import_duty,enacted,2024-07-01,all,Reduces EV duty from 25% to 10%,TRA

ROW 12:
TZ,2025,National EV Policy Framework,regulatory,target,enacted,2025-06-01,all,Four-pillar framework: localize, scale, synergize, enable,Ministry of Transport

ROW 13:
TZ,2026,EWURA E-Mobility Guidelines,regulatory,standard,enacted,2026-01-01,all,Fast charging every 100km along corridors,EWURA

ROW 14:
BI,2027,ICE Vehicle Import Ban,regulatory,ban,announced,2027-01-01,all,Plans to ban ICE vehicle imports from 2027,Ministry of Environment

ROW 15:
BI,2024,EV VAT and Customs Exemption,fiscal,VAT,enacted,2024-01-01,all,EVs exempt from VAT and customs duty,OBR

ROW 16:
BI,2024,Solar Charging Station Pilot,regulatory,infrastructure,enacted,2024-06-01,all,First solar charging station in Bujumbura,Ministry of Energy

ROW 17:
SS,2024,No EV Policy,regulatory,absent,absent,,all,No dedicated EV policy framework,Ministry of Transport

ROW 18:
SS,2024,Hybrid Vehicle Preference,regulatory,informal,informal,,all,Hybrids preferred over pure EVs,Market analysis

ROW 19:
CD,2024,No EV Policy,regulatory,absent,absent,,all,No dedicated EV policy framework,Ministry of Transport

ROW 20:
SO,2024,No EV Policy,regulatory,absent,absent,,all,No dedicated EV policy framework,Ministry of Transport

ROW 21:
SO,2024,Nascent Import Market,regulatory,informal,informal,,all,Small-scale importers only; no incentives,Market analysis

In [30]:
# Get the existing records from policy_inventory
rows = cursor.execute("""
    SELECT * FROM policy_inventory
""").fetchall()

fixed_data = []

for row in rows:
    text = row[0]

    # Split the first 8 commas only
    parts = text.split(",", 8)

    # First 8 fields are fixed
    first_8 = parts[:8]

    # The remaining part contains description + data_source
    description, data_source = parts[8].rsplit(",", 1)

    fixed_data.append(first_8 + [description, data_source])

# Create corrected DataFrame
columns = [
    "country_iso",
    "year",
    "enacted_policy_instrument",
    "instrument_type",
    "category",
    "status",
    "effective_date",
    "vehicle_segment",
    "description",
    "data_source"
]

df_policy = pd.DataFrame(fixed_data, columns=columns)

print("Shape:", df_policy.shape)
display(df_policy)

Shape: (22, 10)

,country_iso,year,enacted_policy_instrument,instrument_type,category,status,effective_date,vehicle_segment,description,data_source
0,KE,2023,Finance Act 2023 EV VAT Exemption,fiscal,VAT,enacted,2023-07-01,all,Exempts EVs from 16% VAT,Kenya Gazette
1,KE,2023,Finance Act 2023 EV Duty Reduction,fiscal,import_duty,enacted,2023-07-01,all,Reduces EV import duty from 25% to 10%,Kenya Gazette
2,KE,2024,National E-Mobility Policy,regulatory,target,draft,2024-01-01,all,5% EV adoption by 2030,MoR&T
3,KE,2024,EPRA Charging Infrastructure Guidelines,regulatory,standard,enacted,2024-03-01,all,Technical standards for charging stations,EPRA
4,RW,2024,Rwanda EV Incentive Framework,fiscal,VAT,enacted,2024-01-01,all,EVs exempt from VAT and import duty,RRA
5,RW,2025,Kigali ICE Motorcycle Ban,regulatory,ban,enacted,2025-01-01,2W,Bans new ICE motorcycle registrations in Kigali,RURA
6,RW,2024,National E-Mobility Strategy,regulatory,target,enacted,2024-06-01,all,Targets 20% EV penetration by 2030,MININFRA
7,UG,2024,National E-Mobility Strategy,regulatory,target,enacted,2024-06-01,2W,20% EV imports by 2030,MoWT
8,UG,2024,EV Import Duty Exemption,fiscal,import_duty,enacted,2024-07-01,all,Full duty exemption for EVs,URA
9,UG,2025,Kampala E-Motorcycle Mandate,regulatory,target,proposed,2026-01-01,2W,Proposed 100% electric motorcycle target,KCCA
10,TZ,2024,Vehicle Registration Amendment,regulatory,standard,enacted,2024-07-01,all,Explicitly includes EVs in registration law,TRA
11,TZ,2024,EV Import Duty Reduction,fiscal,import_duty,enacted,2024-07-01,all,Reduces EV duty from 25% to 10%,TRA
12,TZ,2025,National EV Policy Framework,regulatory,target,enacted,2025-06-01,all,"Four-pillar framework: localize, scale, synerg...",Ministry of Transport
13,TZ,2026,EWURA E-Mobility Guidelines,regulatory,standard,enacted,2026-01-01,all,Fast charging every 100km along corridors,EWURA
14,BI,2027,ICE Vehicle Import Ban,regulatory,ban,announced,2027-01-01,all,Plans to ban ICE vehicle imports from 2027,Ministry of Environment
15,BI,2024,EV VAT and Customs Exemption,fiscal,VAT,enacted,2024-01-01,all,EVs exempt from VAT and customs duty,OBR
16,BI,2024,Solar Charging Station Pilot,regulatory,infrastructure,enacted,2024-06-01,all,First solar charging station in Bujumbura,Ministry of Energy
17,SS,2024,No EV Policy,regulatory,absent,absent,,all,No dedicated EV policy framework,Ministry of Transport
18,SS,2024,Hybrid Vehicle Preference,regulatory,informal,informal,,all,Hybrids preferred over pure EVs,Market analysis
19,CD,2024,No EV Policy,regulatory,absent,absent,,all,No dedicated EV policy framework,Ministry of Transport
20,SO,2024,No EV Policy,regulatory,absent,absent,,all,No dedicated EV policy framework,Ministry of Transport
21,SO,2024,Nascent Import Market,regulatory,informal,informal,,all,Small-scale importers only; no incentives,Market analysis

In [31]:
print(df_policy.iloc[12])

country_iso                                                                 TZ
year                                                                      2025
enacted_policy_instrument                         National EV Policy Framework
instrument_type                                                     regulatory
category                                                                target
status                                                                 enacted
effective_date                                                      2025-06-01
vehicle_segment                                                            all
description                  Four-pillar framework: localize, scale, synerg...
data_source                                              Ministry of Transport
Name: 12, dtype: str

In [32]:
print(df_policy.iloc[21])

country_iso                                                         SO
year                                                              2024
enacted_policy_instrument                        Nascent Import Market
instrument_type                                             regulatory
category                                                      informal
status                                                        informal
effective_date
vehicle_segment                                                    all
description                  Small-scale importers only; no incentives
data_source                                            Market analysis
Name: 21, dtype: str

In [33]:
cursor.execute("""
DROP TABLE IF EXISTS policy_inventory_backup;
""")

cursor.execute("""
CREATE TABLE policy_inventory_backup AS
SELECT * FROM policy_inventory;
""")

conn.commit()

print("Backup created successfully.")

Backup created successfully.

In [34]:
df_policy.to_sql(
    "policy_inventory",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()

print("policy_inventory has been corrected and saved.")

policy_inventory has been corrected and saved.

In [20]:
pow = pd.read_sql("""SELECT * FROM power_systems""", conn)
pow.head()

,country_iso,year,installed_capacity_mw,generation_hydro_pct,generation_solar_pct,generation_wind_pct,generation_thermal_pct,generation_other_pct,national_access_rate,urban_access_rate,rural_access_rate,peak_demand_mw,reserve_margin_pct,grid_emission_factor,data_source
0,KE,2024,3100.5,35,25,15,20,5,76,95,55,2200,40,0.15,EPRA/KPLC
1,RW,2024,195.0,45,10,5,35,5,65,90,45,150,30,0.35,REG
2,UG,2024,1250.0,80,5,0,15,0,45,85,30,900,38,0.12,UETCL
3,TZ,2024,3000.0,40,5,2,50,3,40,80,25,2000,50,0.45,TANESCO
4,BI,2024,100.0,90,2,0,8,0,12,50,5,80,25,0.08,REGIDESO

In [21]:
pow.columns

Index(['country_iso', 'year', 'installed_capacity_mw', 'generation_hydro_pct',
       'generation_solar_pct', 'generation_wind_pct', 'generation_thermal_pct',
       'generation_other_pct', 'national_access_rate', 'urban_access_rate',
       'rural_access_rate', 'peak_demand_mw', 'reserve_margin_pct',
       'grid_emission_factor', 'data_source'],
      dtype='str')